apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-container
        image: python:3.9-slim 
        command: ["/bin/sh", "-c", "echo 'K8s Działa' > index.html; python -m http.server 5000"]
        ports:
        - containerPort: 5000